# Generated by Django 4.2.15 on 2024-09-24 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0004_emulador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rom",
            name="emulador",
        ),
    ]
