# Generated by Django 4.2.15 on 2024-10-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0011_remove_rom_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="emulador",
            name="emu_file",
            field=models.FileField(blank=True, null=True, upload_to="emuladores/"),
        ),
    ]
