# Generated by Django 4.2.15 on 2024-10-15 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0012_emulador_emu_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="rom",
            name="categoria",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                to="roms.categoria_jogo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rom",
            name="emulador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="roms.emulador",
            ),
            preserve_default=False,
        ),
    ]
