# Generated by Django 4.2.15 on 2024-10-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0018_denuncia_moderacao_notificacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name="topico",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="roms.tags"),
        ),
    ]
