# Generated by Django 4.2.15 on 2024-11-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0023_inserir_categoriasforum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mensagem",
            name="lida",
        ),
    ]
