# Generated by Django 4.2.15 on 2024-11-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0024_remove_mensagem_lida"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topico",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
        migrations.AddField(
            model_name="topico",
            name="tags",
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
