# Generated by Django 4.2.15 on 2024-11-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0025_remove_topico_tags_delete_tags_topico_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topico",
            name="tags",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
