# Generated by Django 4.2.15 on 2024-12-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0026_alter_topico_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificacao",
            name="user",
        ),
        migrations.AddField(
            model_name="comentario",
            name="comentario_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="topico",
            name="topico_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Moderacao",
        ),
        migrations.DeleteModel(
            name="Notificacao",
        ),
    ]
